import type { Metadata } from "next";
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import NewEventForm from "@/components/dashboard/newEvent/newEventFile"; 


export const metadata: Metadata = {
  title: "Dashboard/addevent",
  description: "Generated by create next app",
};


export default function NewEventRoute() {

  return (
    <div className="w-full h-full flex flex-1 items-center justify-center">
      <Card>
        <CardHeader>
          <CardTitle>Add new appointment type</CardTitle>
          <CardDescription>
            Create new appointment type that allows people to book you!
          </CardDescription>
        </CardHeader>
        <NewEventForm/>
      </Card>
    </div>
  );
}